neiman-marcus/terraform-aws-jenkins-ha-agents

README.md
examples/full/README.md
examples/full/init/custom_plugins.cfg
examples/full/main.tf
init/master-runcmd.cfg
main.tf
variables.tf

Add ability to use custom plugins, outside of the module.

Feature: Custom Plugins.

---

README.md
variables.tf

v1.1.1: Jenkins LTS version 2.176.1 and SWARM version 3.17

---

README.md
outputs.tf

Additional outputs for route53 zone id.

---

.gitignore
README.md
examples/full/terraform.tfvars
examples/full/variables.tf
init/agent-runcmd.cfg
init/master-runcmd.cfg
init/master-write-files.cfg
main.tf
variables.tf

- Updated Jenkins to latest LTS.
- Added pip3 as default.
- Cleaned up documentation.
- Moved some items around to be clean.
Tested deployment. Tested upgrade from v1.1.3.

v1.1.4 - Update Jenkins, add pip3, cleanup.

---

README.md
examples/full/main.tf
examples/full/terraform.tfvars
examples/full/variables.tf
init/master-runcmd.cfg
init/master-write-files.cfg
main.tf
variables.tf

* Add auto update plugins feature.
* Modified unhealthy threshold for the master instance.
* Tested deployment in nonprod.
* Tested upgrade from v1.1.4 in nonprod.

v1.2.0 - Auto update plugins.

---

init/agent-runcmd.cfg
init/master-runcmd.cfg

Python3 installation is broken. Resolved issue. Please expedite review to push this critical bug fix.

Critical Bug Fix: Resolve python installation issue.

---

README.md
examples/full/main.tf
examples/full/terraform.tfvars
examples/full/variables.tf
examples/minimum/main.tf
main.tf
variables.tf

* Enabling agent volume variable
* Delete EBS on termination enabled
* Extend EFS to include provisoned throughput. See  #17

V2.2.0 volume modification

---

README.md
examples/full/main.tf
examples/full/terraform.tfvars
examples/full/variables.tf
examples/minimum/main.tf
variables.tf

Update to Jenkins LTS 2.190.2

---

README.md
examples/full/main.tf
examples/minimum/main.tf
outputs.tf

Adding two outputs for the iam roles.

Adding role outputs.

---

README.md
examples/full/main.tf
examples/full/terraform.tfvars
examples/full/variables.tf
examples/minimum/main.tf
variables.tf

Update jenkins version.

---

main.tf

Add HTTP listener to redirect to HTTPS

---

main.tf
variables.tf

The variable names seem a bit off, let me know if you have suggestions.

Make scale number variables for better customization

---

README.md
examples/full/main.tf
examples/full/terraform.tfvars
examples/full/variables.tf
init/agent-runcmd.cfg
init/master-runcmd.cfg
variables.tf

minor changes, upgrade jenkins version.

---

README.md
examples/full/main.tf
examples/full/terraform.tfvars
examples/full/variables.tf
main.tf
variables.tf

Add options for the ASG names. Resolves #23.

Add asg name options.

---

README.md
examples/full/main.tf
examples/full/terraform.tfvars
examples/full/variables.tf
main.tf
variables.tf

* Adjust CPU alarm threshold
* Fix documentation

V2.4.2 cpu alarm adjustment

---

README.md
examples/full/main.tf
examples/full/terraform.tfvars
examples/full/variables.tf
init/master-write-files.cfg
main.tf
variables.tf

* Add agent launch template
* Allows for default spot price (on-demand max)
* Multiple spot instance overrides to help ensure spot instances are available
* Deprecate tf 0.11 support
* Update documentation and examples

Add agent lt.

---

README.md
examples/full/terraform.tfvars
examples/full/variables.tf
main.tf
outputs.tf
variables.tf

* Master launch template
* More flexibility and speed with deployments
* Further cleanup of outputs.

Add master launch template

---

.github/workflows/main.yaml

Add tf lint actions for all PR's.

Add linting actions for all PRs.

---

README.md
examples/full/main.tf

* Update documentation to format correctly on the Terraform Registry.

Documentation update

---

README.md
examples/full/main.tf
examples/full/terraform.tfvars
examples/full/variables.tf
main.tf
variables.tf

* Add retention days variable to accommodate consumers with different retention requirements.
* Update Swarm to v3.21

Cloudwatch Retention Days Enhancement

---

README.md
examples/full/terraform.tfvars
examples/full/variables.tf
main.tf
variables.tf

* Upgrade jenkins to 2.235.4
* Fix cloudwatch bug where TF destroyed the CW log group, but then the instance recreated it.

Jenkins upgrade && bugfix

---

README.md
examples/full/terraform.tfvars
examples/full/variables.tf
variables.tf

- Update jenkins version
- Update swarm version

Update jenkins version

---

main.tf
variables.tf

added CreateLogGroup permission to agent and master

bumped jenkins version to 2.263.4

---

variables.tf

Changing Jenkins Version to 2.332.3

changed jenkins version from 2.332.2 to 2.332.3

---

init/agent-runcmd.cfg
init/master-runcmd.cfg
variables.tf

Bumped version of Swarm to 3.34
Bumped version of Java to 11

Bumped version of Jenkins to 2.346.3

---

init/agent-runcmd.cfg

added curl directive to follow redirects

issue#81 updated curl to follow redirects

---

init/master-runcmd.cfg

This PR is a try to give user choice use predefined list of plugins or use own list and do not use predefined ones.

Add more control under plugins installed
